id: PC587C685
initial_creation_type: input
source_metadata:
  title: Haribhadra Series
  language: bo
  description: 'Texts by and about the celebrated master of Prajñāpāramitā Haribhadra
    (seng ge bzang po):'
  volume:
    7a3008d7934245f8a5e88cc637573981:
      title: Guru Yoga of the Great Learned and Accomplished Ācārya Haribhadra
      parent: Guru Yoga
created_at: '2022-03-01T02:15:54.411240'
last_modified_at: '2022-03-01T02:15:54.411242'
statistics:
  total_words: 599
  total_non_words: 72
quality:
  non_words_ratio: 0.12
